describe('Sketch Item', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.clickButton('Master reset')
    cy.clickButton('Add Sketch')
  })

  it('Toggling "watched" input should toggle button between "Remove" and "Add to Archive"', () => {
    cy.get('[type="checkbox"]')
      .check()
    cy.contains('Remove')
      .should('not.exist')
    cy.contains('Add to Archive')
      .should('exist')
    cy.get('[type="checkbox"]')
      .uncheck()
    cy.contains('Remove')
      .should('exist')
    cy.contains('Add to Archive')
      .should('not.exist')
  })

  it('Selecting "rating" should change the value', () => {
    cy.get('[data-cy=rating-select]')
      .select('3')
      .should('have.value', '3')
      .select('4')
      .should('have.value', '4')
      .select('1')
      .should('have.value', '1')
  })

  it('Clicking "Add to Archive" should move the sketch to archive list', () => {
    cy.get('[data-cy=rating-select]')
      .select('3')
    cy.get('[type="checkbox"]')
      .check()
    cy.clickButton('Add to Archive')
    cy.get('[data-cy=list] ul')
      .children()
      .should('have.length', 0)
    cy.clickButton('Toggle Archive')
    cy.get('[data-cy=archive] ul')
      .children()
      .should('have.length', 1)
  })
})