describe('Sketch Item', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.clickButton('Master reset')
    cy.clickButton('Add Sketch')
  })

  it('Toggling "watched" input should toggle button between "Remove" and "Add to Archive"', () => {
    cy.get('[type="checkbox"]')
      .check()
    cy.contains('Remove')
      .should('not.exist')  
    cy.contains('Add to Archive')
      .should('exist')
    cy.get('[type="checkbox"]')
      .uncheck()
    cy.contains('Remove')
      .should('exist')  
    cy.contains('Add to Archive')
      .should('not.exist')  
  })

  it('Incrementing and decrementing "rating" input should change the value', () => {
    cy.get('[type="number"]')
      .type('3')
      .should('have.value', '3')
      .type('{uparrow}')
      .should('have.value', '4')
      .type('{downarrow}')
      .should('have.value', '3')
  })

  it('The rating can be in range between 0 and 10', () => {
    cy.get('[type="number"]')
      .type('0')
      .type('{downarrow}')
      .should('have.value', '0')
      .clear()
      .type('10')
      .type('{uparrow}')
      .should('have.value', '10')
      .clear()
      .type('20')
      .should('have.value', '10')
      .clear()
      .type('-8')
      .should('have.value', '0')
      .clear()
      .type('2^$*&$')
      .should('have.value', '2')
      .clear()
      .type('00000')
      .should('have.value', '0')
  })

  it('Clicking "Add to Archive" should move the sketch to archive list', () => {
    cy.get('[type="number"]')
      .type('5')
    cy.get('[type="checkbox"]')
      .check()
    cy.clickButton('Add to Archive')
    cy.get('.list_container__3I0dz ul')
      .children()
      .should('have.length', 0)
    cy.clickButton('Toggle Archive')
    cy.get('.archive_container__2mTwC ul')
      .children()
      .should('have.length', 1)
  })
})