export const data = [
  'The Accidents Sketch',
  'Advertisements',
  'The Aftershave Sketch',
  'The Agatha Christie Sketch',
  'The Airline Pilots sketch (from How to Irritate People)',
  'Albatross',
  'A Minute Passed',
  'Anagram Quiz',
  'Ant Complaints',
  'Apology for Violence and Nudity',
  'Apology [Salad Days]',
  'Apology [Politicians]',
  'Appeal on Behalf of Extremely Rich People',
  'The Architect Sketch',
  'Are You Embarrassed Easily?',
  'The Argument Clinic',
  'Army Captain as Clown',
  'The Army Protection Racket',
  'Art Critic - the Place of the Nude',
  'Art Gallery / Art Critic',
  'Arthur Tree',
  'Arthur Two-Sheds Jackson',
  'At Home With the Ant and Other Pets',
  'Attila the Bun',
  'The Attila the Hun Show',
  'Attila the Nun',
  'The Audit',
  'Australian Table Wines',
  'Background to History',
  'Bank Robber/Lingerie Shop',
  'The Banter Sketch',
  'Batley Townswomens Guild Presents the First Heart Transplant',
  'Batley Townswomans Guild presents the Battle of Pearl Harbour',
  'The Batsmen of the Kalahari',
  'The Battle of Trafalgar',
  'The BBC is Short of Money',
  'BBC News (Handovers)',
  'BBC Programme Planners',
  'Be a Great Actor',
  'Bells',
  'Bicycle Repairman',
  'Biggles Dictates a Letter',
  'The Bishop',
  'The Bishop of Leicester',
  'A Bishop Rehearsing',
  'Blackmail',
  'Blancmanges Playing Tennis',
  'Blood, Devastation, Death, War and Horror',
  'Blood Donor',
  'Bogus Psychiatrists',
  'Bomb on Plane',
  'A Book at Bedtime - Redgauntlet',
  'The Bookshop',
  'Boxing Commentary',
  'Boxing Match Aftermath',
  'Boxing Tonight - Jack Bodel v. Sir Kenneth Clark',
  'Brigadier and Bishop',
  'The British Well-Basically Club',
  'The Bruces Sketch',
  'Bull-Fighting',
  'Burgler/Encyclopaedia Salesman',
  'Burying the Cat',
  'Bus Conductor Sketch',
  'Buying a Bed',
  'Buying an Ant',
  'Camel Spotting/Train Spotting',
  'Camp Square-Bashing',
  'Charwoman',
  'The Cheap-Laughs',
  'The Cheese Shop',
  'Chemist Sketch/Words Not to be Used Again',
  'Childrens Stories',
  'Childrens Interview',
  'A Choice of Viewing',
  'Climbing the North Face of Uxbridge Road',
  'Come Back to My Place',
  'Commercials',
  'Communist Quiz (World Forum)',
  'Complaints Department',
  'Confuse-a-Cat',
  'Conjuring Today',
  'Courtmartial [Basinstoke in Westphalia]',
  'Court Scene (Charades)',
  'Court Scene (Witness in Coffin / Cardinal Richelieu)',
  'Credits of the Year',
  'Cricket Match (Assegais)',
  'Crunchy Frog (Whizzo Chocolate)',
  'Current Affairs',
  'The Cycling Tour',
  'Dads Doctors and Other Interesting Shows',
  'David Nivens Fridge',
  'The Dead Bishop Sketch',
  'The Death of Mary, Queen of Scots',
  'Deja Vu',
  'Dennis Moore',
  'Dennis Moore Rides Again',
  'Dentists (Live from Epsom)',
  'Department Store',
  'Different Endings',
  'The Dinosaur Sketch (Anne Elk)',
  'The Dirty Vicar Sketch',
  'Doctor',
  'A Doctor Whose Patients are Stabbed by His Nurse',
  'Documentary on Ants',
  'Documentary on Boxer',
  'A Duck, a Cat and a Lizard (Discussion)',
  'The Dull Life of a City Stockbroker',
  'Dung/Dead Indian',
  'Eating Dog',
  'Eclipse of the Sun',
  'Eighteenth Century Social Legislation',
  'The Election Night Special',
  'Elephantoplasty',
  'Elizabethan Pornography Smugglers',
  'The Epsom Furniture Race',
  'Erotic Film',
  'Europolice Song Contest / Bing Tiddle Tiddle Bong (song)',
  'Expedition to Lake Pahoe',
  'Exploding Version of the Blue Danube',
  'Face the Press',
  'A Fairy Tale',
  'Famous Deaths',
  'Father-in-Law',
  'Film Director (Teeth)',
  'Film Trailer',
  'Finians Rainbow (staring the man from the off-licence)',
  'Fire Brigade',
  'The First Man to Jump the Channel',
  'The First Underwater Production of Measure for Measure',
  'Fish License',
  'Fish-Slapping Dance',
  'Flying Lessons',
  'Flying Sheep',
  'The Four Yorkshiremen',
  'The Free Repetition of Doubtful Words Sketch, By an Underrated Author',
  'French Lecture on Sheep-Aircraft',
  'French Subtitled Film',
  'The Funniest Joke in the World',
  'Gestures to Indicate Pauses in Televised Talk',
  'The Golden Age of Ballooning : George III',
  'The Golden Age of Balloning: Louis XIV',
  'The Golden Age of Ballooning: Montgolfier Brothers',
  'The Golden Age of Ballooning: Zeppelin',
  'Gorilla Librarian',
  'Great Actors',
  'Gumby Brain Specialist',
  'Gumby Crooner',
  'Gumby Flower Arranging',
  'Gumby Theater',
  'The Haggis Poem (a.k.a. The Horace Poem)',
  'Hairdressers Climb Mt. Everest',
  'Hamlet and Ophelia',
  'Hells Grannies',
  'Hermits',
  'Hijacked Plane [to Luton]',
  'Hitting on the Head Lessons',
  'Historical Impersonations',
  'Homicidal Barber',
  'Hospital for Over-Actors',
  'Hospital Run by R.S.M.',
  'Housing Project Built by Characters From Nineteenth-Century English Literature',
  'How Far Can a Minister Fall?',
  'How Not To Be Seen',
  'How to Do It',
  'How to Feed a Goldfish',
  'How to Give Up Being a Mason',
  'How to Rid the World of All Known Diseases',
  'How Your Body Works',
  'The Hungarian Phrasebook',
  'Hunting Film',
  'Icelandic Honey Week',
  'The Ideal Loon Exhibition',
  'The Idiot in Society',
  'If - a Film by Mr. Dibley',
  'The Insurance Sketch',
  'Interesting People',
  'International Wife-Swapping',
  'Interruptions',
  'Interview with Anne Elk [Dinosaurs]',
  'Interview with Carl French [Marilyn Monroe]',
  'Interview With Sir Edward Ross',
  'Is There?...Life After Death?',
  'Italian Lesson',
  'It All Happened on the 11:20 From Hainault',
  'Its a Living',
  'Its a Mans Life in the Modern Army',
  'Its Wolfgang Amamdeus Mozart',
  'Jockey Interviews',
  'Johann Gambolputty',
  'Joke and Novelties Salesman',
  'Julius Caesar on an Aldis Lamp',
  'Kamikaze Scotsman',
  'Ken Shabby',
  'Kilimanjaro Expedition (Double Vision)',
  'Killer Sheep',
  'Language Laboratory',
  'Leapy Lee',
  'Letters [Lavatorial Humor]',
  'Life and Death Struggles',
  'Life of Tschaikowsky',
  'Light Entertainment Awards with Dickie Attenborough',
  'Light Entertainment Awards Part 2',
  'Live from the Grill-o-Mat Snack Bar, Paignton',
  'Living Room on Pavement',
  'Lifeboat [Old Ladys]',
  'The Lifeboat Sketch [Cannibalism]',
  'Literary Football Discussion',
  'Llamas',
  'The Logician',
  'M1 Interchange Built by Characters From Paradise Lost',
  'Man Turns Into Scotsman / Police Station',
  'The Man Who Collects Birdwatchers Eggs',
  'The Man Who Contradicts People',
  'The Man Who is Alternately Rude and Polite',
  'The Man Who Finishes Other Peoples Sentences',
  'The Man Who Makes People Laugh Uncontrollably',
  'The Man Who Says Words in the Wrong Order',
  'The Man Who Speaks in Anagrams',
  'The Man with Three Buttocks',
  'A Man with Two Noses',
  'Marilyn Monroe [Interview with Carl French]',
  'Marriage Guidance Counsellor',
  'Mary Recruitment Office',
  'Me, Doctor',
  'The Mens Being-Eaten-By-A-Crocodile Contest',
  'Merchant Banker',
  'Michelangelo and the Pope',
  'The Minister for Not Listening to People',
  'The Ministry of Silly Walks',
  'Molluscs - Live TV Documentary',
  'The Money Programme',
  'Mortuary Hour',
  'Mosquito Hunters',
  'The Most Awful Family in Britain',
  'Motor Insurance',
  'Mountaineer',
  'The Mouse Problem',
  'Mr. Attila the Hun',
  'Mr. Neutron',
  'Mr. Neutron is Missing',
  'Mr. Neutron is Still Missing',
  'Mr. Neutron is Found',
  'Mr. Neville Shunt',
  'Mrs Niggerbaiter Explodes',
  'Mr. Phone In',
  'Mrs. Thing and Mrs. Entity',
  'Musical Mice',
  'Mystico and Janet - Flats Built by Hypnosis',
  'A Naked Man',
  'Nationwide',
  'Neurotic Announcers',
  'New Brain from Currys',
  'New Cooker Sketch',
  'Newsflash (Germans)',
  'The News For Gibbons',
  'The News For Parrots',
  'The News For Wombats',
  'The News With Richard Baker',
  'Newsreader Arrested',
  'Non-Illegal Robbery',
  'The North Minehead Bye Election',
  'No Time To Lose',
  'Novel Writing',
  'Nudge Nudge',
  'Off-Licence [including more Dennis Moore]',
  'Old Lady Snoopers',
  'The Olympic Hide and Seek Final',
  'Open Field Farming Songs',
  'Operating Theatre [Squatters]',
  'The Oscar Wilde Sketch',
  'Our Eamonn',
  'The Package Tour Complaint',
  'Pantomime Horses',
  'The Pantomine Horse is a Secret Agent Film',
  'Party Hints with Veronica Smalls',
  'Party Political Broadcast (choreographed)',
  'Pasolinis The Third Test Match',
  'The Penguin on the Television',
  'Penguins',
  'The Penultimate Supper (John Cleese/Johnathan Lynne)',
  'People Falling From Buildings',
  'The Petshop Sketch (Dead Parrot Version)',
  'A Pet Shop Somewhere Near Melton Mowbray (Terriers, Cats and Fish Version)',
  'Philip Jenkinson on Cheese Westerns',
  'Picasso / Cycling Race',
  'Piston Engine (A Bargain)',
  'The Poet McTeagle',
  'Poetry Reading (Ants)',
  'Poets',
  'Police Constable Pan-Am',
  'Police Helmets',
  'Policemen Make Wonderful Friends',
  'Police Raid / Letter and Vox Pops',
  'Police Station (Silly Voices)',
  'Political Broadcast',
  'The Pornographic Bookshop',
  'Post Box Ceremony',
  'Prejudice',
  'Probe Around on Crime',
  'Prices on the Planet Algon',
  'Programme Titles Conference',
  'Psychiatrist Milkman',
  'Psychiatry - Silly Sketch',
  'The Public are Idiots',
  'Quiz programme - Wishes',
  'Queen Victoria Handicap',
  'Ramsey MacDonald Striptease',
  'Ralph Melish (Nothing Happened)',
  'Ratcatcher',
  'Raymond Luxury Yacht Interview',
  'Rear Window - a Film by Mr Dibley',
  'Red Indian in Theatre',
  'The Refreshment Room at Bletchley',
  'Registrar (Wife-Swapping)',
  'The Registry Office',
  'Repeating Groove',
  'Restaurant (Abuse/Cannibalism)',
  'The Restaurant Sketch (Dirty Fork)',
  'Right-Thinking People',
  'Rival Documentaries',
  'Rock Notes',
  'A Room in Polonius House',
  'Royal Festival Hall Concert',
  'Salvation Fuzz (Dead Bishop)',
  'Sam Peckinpahs Salad Days',
  'Science Fiction Sketch',
  'School Prize-Giving',
  'A Scotsman on a Horse',
  'Seashore Interlude Film',
  'Secretary of State Striptease',
  'Secret Service Dentists',
  'Self-defense Against Fresh Fruit',
  'The Semaphore Version of Wuthering Heights',
  'Seven Brides for Seven Brothers',
  'Sherry-Drinking Vicar',
  'Show Jumping (Musical)',
  'The Show So Far',
  'The Silliest Interview Weve Ever Had / The Silliest Sketch Weve Ever Done',
  'Silly Disturbances (The Rev. Arthur Belling)',
  'Silly Job Interview / Careers Advisory Board',
  'Silly Noises',
  'The Smuggler',
  'Spectrum - Talking About Things',
  'The Society for Putting Things on Top of Other Things',
  'Spam',
  'Spanish Inquisition',
  'Spot the Looney',
  'Stake Your Claim',
  'Stolen Newsreader',
  'Stonehenge',
  'Storage Jars',
  'Strangers in the Night',
  'String',
  'St. Victor',
  'Submarine',
  'The "Summarize Proust Competition"',
  'Take Your Pick',
  'The Tale of the Piranha Brothers',
  'Tax on Thingy',
  'Teddy Salad (CIA Agent)',
  'Ten Seconds of Sex',
  'Test Match',
  'Thames TV Introduction',
  'Thripshaws Disease',
  'Tiger Club',
  'The Time on BBC 1',
  'Timmy Williams Interview',
  'Tobacconists (Prostitute Advertisement)',
  'Today in Parliament',
  'Top of the Form (from The Secret Policemans Other Ball)',
  'Tory Housewives Clean-up Campaign',
  'Toupee Department',
  'Trailer',
  'Travel Agent (TV series short version)',
  'Travel Agent (Hollywood Bowl long version)',
  'The Trial',
  'Trivializing the War',
  'Tudor Jobs Agency',
  'Tuesday Documentary',
  'Tunnelling from Godalming to Java',
  'TV4 or not TV4 Discussion',
  'Twentieth-Century Vole',
  'Undertakers Film 1',
  'Undertakers Film 2',
  'The Undertakers Sketch',
  'Undressing in Public',
  'Unexploded Scotsmen',
  'The Upperclass "Twit of the Year"',
  'Up Your Pavement',
  'Vicar (Salesman)',
  'Visitors from Coventry',
  'The Vocational Guidance Counselor',
  'Vox Pops on Politicians',
  'Vox Pops on Smuggling',
  'The Wacky Queen',
  'Wainscotting',
  'The Walking Tree of Dahomey (with David Attenborough)',
  'What the Stars Foretell',
  'When Does A Dream Begin? (Song)',
  'Whizzo Butter',
  'The Whizzo Chocolate Company (Crunchy Frog)',
  'The Woody Sketch',
  'Word Association Football',
  'Working-Class Playwright',
  'World Forum (Communist Quiz)',
  'World War I Soldier / Stuck Record',
  'The Wrestling Epilogue ',
]